language: swift
osx_image: xcode11.1

matrix:
  include:
  - name: iOS
    xcode_project: Bees.xcodeproj
    xcode_scheme: Bees
    xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 11
  - name: macOS
    xcode_project: Bees.xcodeproj
    xcode_scheme: Bees
    xcode_destination: platform=macOS
